# Generated by Django 2.2.1 on 2019-12-24 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
                ('trn', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=254)),
                ('district', models.CharField(max_length=254)),
                ('parish', models.CharField(choices=[('', 'Choose...'), ('St. Andrew', 'Kingston'), ('Portland', 'St. Thomas'), ('St. Catherine', 'St. Mary'), ('St. Ann', 'Manchester'), ('Clarendon', 'Hanover'), ('Westmoreland', 'St. James'), ('Trelawny', 'St. Elizabeth')], max_length=15)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='MailClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('send_it', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
